name: Docker-Linuxes

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:

  ubuntu-18-04:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_ubuntu_18.04 -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"

  ubuntu-20-04:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_ubuntu_20.04 -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"
  
  ubuntu-22-04:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_ubuntu_22.04 -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"

  ubuntu-22-10:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_ubuntu_22.10 -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"

  ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_ubuntu_latest -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"

  centos7:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_centos_7 -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"

  redhat-ubi8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_redhat_ubi8 -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"

  redhat-ubi9:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_redhat_ubi9 -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"

  fedora-36:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_fedora_36 -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"
      
  fedora-37:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_fedora_37 -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"

  fedora-38:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_fedora_38 -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"

  fedora-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --rm -f ./docker/Dockerfile_fedora_latest -t ctl:latest .

    - name: Run unit tests (ctest) within the Docker image
      run: docker run ctl:latest sh -c "cd ./build && ctest"
